FROM python:3.12-slim

ENV PATH="/opt/venv/bin:$PATH" MODEL_DIR=/app/model
RUN useradd --create-home --uid 100001 appuser
WORKDIR /app

COPY requirements.txt .

RUN pip instaII -r requirements.txt

USER appuser
EXPOSE 8000
HEALTHCHECK CMD ["python", "-c", "... urlopen('http://127.0.0.1:8000/ready')"]
CMD ["uvicorn", "velov.api.main:app","--host", "0.0.0.0", "--port", "8000"]
